include(
    ":common:root",
    ":common:utils",
    ":common:compose-ui",
    ":common:main",
    ":common:create",
    ":common:details",
    ":android",
    ":common:di",
    ":common:data",
    ":common:auth",
    ":common:amplify"
)